FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app

COPY pom.xml ./
COPY src ./src

RUN mvn -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app

COPY --from=build /app/target/petstore-backend-1.0.0.jar ./petstore-backend-1.0.0.jar
COPY entrypoint.sh ./entrypoint.sh

EXPOSE 8080

ENTRYPOINT ["sh", "/app/entrypoint.sh"]